// Generated by LiveScript 1.3.1
(function(){
  var express, path, app;
  express = require('express');
  path = require('path');
  app = express();
  app.set('port', process.env.PORT || 8080);
  app.use(express['static'](path.join(__dirname, '')));
  app.listen(app.get('port'), '0.0.0.0');
}).call(this);
