// Generated by LiveScript 1.3.1
(function(){
  var fs, jsYaml, basic_english, english_to_hindi, english_to_hindi_basic, i$, ref$, len$, word, hindi;
  fs = require('fs');
  jsYaml = require('js-yaml');
  basic_english = fs.readFileSync('specific_english_nouns.txt', 'utf8');
  english_to_hindi = JSON.parse(
  fs.readFileSync('english_to_hindi.json', 'utf8'));
  english_to_hindi_basic = {};
  for (i$ = 0, len$ = (ref$ = basic_english.split('\n')).length; i$ < len$; ++i$) {
    word = ref$[i$];
    word = word.trim();
    word = word.toLowerCase();
    if (word.indexOf('. ') !== -1) {
      word = word.split('. ')[1];
    }
    hindi = english_to_hindi[word];
    if (hindi != null) {
      if (hindi.indexOf('/') !== -1) {
        continue;
      }
      if (hindi.indexOf('_') !== -1) {
        continue;
      }
      if (hindi.indexOf('[') !== -1) {
        continue;
      }
      if (hindi.indexOf('-') !== -1) {
        continue;
      }
      english_to_hindi_basic[word] = hindi;
    }
  }
  fs.writeFileSync('english_to_hindi_basic.yaml', jsYaml.safeDump(english_to_hindi_basic));
  fs.writeFileSync('english_to_hindi_basic.json', JSON.stringify(english_to_hindi_basic));
}).call(this);
