// Generated by LiveScript 1.3.1
(function(){
  var J, root, alphabets, banned_letters, synthesize_word, set_target_word, switch_word, pick_word, get_next_letter, addLetter, highlight_next, new_word, slice$ = [].slice;
  J = $.jade;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  alphabets = {
    latin: (["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"].concat(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])).join('')
  };
  banned_letters = {
    hindi: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"].concat(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"], ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"], ['.', ',', '/', '-', '_', '?', ',', '.', '^', '(', ')', ':', '[', ']', '\'', '"', '{', '}', '~', '`'])
  };
  synthesize_word = function(word){
    var video_tag;
    video_tag = $('video');
    if (video_tag.length === 0) {
      video_tag = J('video').css({
        display: 'none'
      });
      $('body').append(video_tag);
    }
    video_tag.attr('src', 'http://speechsynth.herokuapp.com/speechsynth?' + $.param({
      lang: 'hi',
      word: word
    }));
    video_tag[0].currentTime = 0;
    return video_tag[0].play();
  };
  set_target_word = function(target_word){
    root.target_word = target_word;
    $('#topword').text(root.target_word);
    root.current_word = [];
    $('#inputarea').text('');
    return $('#english_translation').text(root.hindi_to_english[target_word]);
  };
  switch_word = function(){
    set_target_word(pick_word());
    return highlight_next();
  };
  pick_word = function(){
    var word_idx;
    word_idx = Math.floor(
    Math.random() * root.hindi_words.length);
    return root.hindi_words[word_idx];
  };
  root.current_word = [];
  get_next_letter = function(){
    var num_typed, remaining;
    num_typed = root.current_word.length;
    remaining = slice$.call(root.target_word, num_typed);
    return remaining[0];
  };
  addLetter = function(letter){
    var partial_word;
    if (letter !== get_next_letter()) {
      return;
    }
    root.current_word.push(letter);
    partial_word = root.current_word.join('');
    $('#inputarea').text(partial_word);
    console.log(partial_word);
    synthesize_word(letter);
    setTimeout(function(){
      return synthesize_word(partial_word);
    }, 600);
    return highlight_next();
  };
  highlight_next = function(){
    var next_letter;
    next_letter = get_next_letter();
    if (next_letter == null) {
      switch_word();
      return;
    }
    $('.highlighted').removeClass('highlighted');
    return $('#let' + next_letter).addClass('highlighted');
  };
  new_word = function(){
    var word, letters, i$, len$;
    console.log('new word!');
    word = pick_word();
    letters = Object.keys(letter_frequencies);
    letters = letters.sort(function(a, b){
      return letter_frequencies[a] - letter_frequencies[b];
    }).reverse();
    for (i$ = 0, len$ = letters.length; i$ < len$; ++i$) {
      (fn$.call(this, letters[i$]));
    }
    return highlight_next();
    function fn$(letter){
      $('#keyboard').append(J('.button').text(letter).attr('id', 'let' + letter).click(function(){
        return addLetter(letter);
      }));
    }
  };
  $(document).ready(function(){
    /*
    $.get '/devanagari_letters.yaml', (yamldata) ->
      hindi_letters_to_english = jsyaml.safeLoad yamldata
      hindi_letters = Object.keys hindi_letters_to_english
      console.log hindi_letters
      for letter in hindi_letters
        $('#keyboard').append J('.button').text(letter)
    */
    return $.get('/english_to_hindi.json', function(english_to_hindi){
      var hindi_words, english_words, letter_frequencies, hindi_to_english, english, hindi, skip_word, i$, len$, letter;
      root.english_to_hindi = english_to_hindi;
      root.hindi_words = hindi_words = [];
      root.english_words = english_words = [];
      root.letter_frequencies = letter_frequencies = {};
      root.hindi_to_english = hindi_to_english = {};
      for (english in english_to_hindi) {
        hindi = english_to_hindi[english];
        skip_word = false;
        for (i$ = 0, len$ = hindi.length; i$ < len$; ++i$) {
          letter = hindi[i$];
          if (banned_letters.hindi.indexOf(letter) !== -1) {
            skip_word = true;
          }
        }
        if (skip_word) {
          continue;
        }
        english_words.push(english);
        hindi_words.push(hindi);
        for (i$ = 0, len$ = hindi.length; i$ < len$; ++i$) {
          letter = hindi[i$];
          if (letter_frequencies[letter] == null) {
            letter_frequencies[letter] = 0;
          }
          letter_frequencies[letter] += 1;
        }
        hindi_to_english[hindi] = english;
      }
      set_target_word('हिन्दी');
      return new_word();
    });
  });
}).call(this);
