// Generated by LiveScript 1.3.1
(function(){
  var J, root, alphabets, pick_word, new_word;
  J = $.jade;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  alphabets = {
    latin: (["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"].concat(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])).join('')
  };
  pick_word = function(){
    var word_idx;
    word_idx = Math.floor(
    Math.random() * root.hindi_words.length);
    return root.hindi_words[word_idx];
  };
  new_word = function(){
    var word;
    console.log('new word!');
    word = pick_word();
    return console.log(letter_frequencies);
  };
  $(document).ready(function(){
    return $.get('/english_to_hindi_basic.json', function(english_to_hindi){
      var hindi_words, english_words, letter_frequencies, hindi_to_english, english, hindi, i$, len$, letter;
      root.hindi_words = hindi_words = [];
      root.english_words = english_words = [];
      root.letter_frequencies = letter_frequencies = {};
      root.hindi_to_english = hindi_to_english = {};
      for (english in english_to_hindi) {
        hindi = english_to_hindi[english];
        english_words.push(english);
        hindi_words.push(hindi);
        for (i$ = 0, len$ = hindi.length; i$ < len$; ++i$) {
          letter = hindi[i$];
          if (letter_frequencies[letter] == null) {
            letter_frequencies[letter] = 0;
          }
          letter_frequencies[letter] += 1;
        }
        hindi_to_english[hindi] = english;
      }
      return new_word();
    });
  });
}).call(this);
